### ISSUE TITLE
What is this repo current status?

### ISSUE THREAD

**Issue by nikitos1550** [Biktorgj/linux-4.14-mdm9607#1]
Hi!

I built and run this kernel for mdm9607 ec25-e, and it boots.
I stopped at modem fw boot, as cdsp_loader seems is not finished (by the way, why name changed from adsp_loader?).

I am newbie to qualcomm chipsets and queltec devices, so I have several questions:
- what is this linux tree? is it somehow official src from vendor, or your own port from stock 3.18?
- what are further plans?

P.S. After I tried quectel_eg25_kernel repo, and booted modem via adsp_loader.

**Comment by Biktorgj** [comment]
This is just me expedrimenting. As you said, the kernel is able to boot and get you into a serial console at this point, but mostly doesn't work. Neither does the ADSP loader work, or USB, or audio. 

I got a little further with some stuff, but nothing really works here. The only really working kernel is, as you said, the quectel_eg25_kernel repo, which is older, but every device works as expected (as far as I know ;))
